#Applitacion Configuration
#server:
  #port: 8093

#spring:
  #cloud:
    #loadbalancer:
       #ribbon:
        #enable: false

#logging:
  #pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
#######################################################################################

#server:
 #port: 8093

#spring:
  #application:    #name: shoppingInvoices-service
  #cloud:
    #loadbalancer:
       #ribbon:
        #enable: false

#eureka:
  #client:
    #registerWithEureka: true
    #fetchRegistry: true
    #serviceUrl:
      #defaultZone: http://localhost:8099/eureka/

#logging:
  #pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

#feign:
    #hystrix:
        #enabled: true
    #metrics:
        #enabled: true
    #dashboard:
      #proxyStreamAllowList: "*"
    
#management:
    #endpoints:
        #web:
            #exposure:
                    #include: "*"
